name: Dev Build

on:
  push:
    branches:
      - dev**
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dart Sass
        uses: robinraju/release-downloader@v1
        with:
          repository: 'sass/dart-sass'
          latest: true
          fileName: 'dart-sass-*-linux-x64.tar.gz'
          extract: true
      - name: Add Binary to PATH
        run: |
          echo "$GITHUB_WORKSPACE/dart-sass" >> "$GITHUB_PATH"
      - name: Compile
        run: |
          cd ./src; make
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: |
            ./src/latex-theme/*
