name: Release
on:
  create:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dart Sass
        uses: robinraju/release-downloader@v1
        with:
          repository: 'sass/dart-sass'
          latest: true
          fileName: 'dart-sass-*-linux-x64.tar.gz'
          extract: true
      - name: Add Binary to PATH
        run: |
          echo "$GITHUB_WORKSPACE/dart-sass" >> "$GITHUB_PATH"
     - name: Compile
        run: |
          cd ./src; make all-and-compress
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            ./src/latex-theme/*.zip
